apiVersion: v1
kind: Service
metadata:
  name: dns-service-v4
  namespace: bind
spec:
  selector:
    app: dns-bind
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 192.168.10.241
